# Generated by Django 4.2.7 on 2023-12-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
