# Generated by Django 4.2.7 on 2023-12-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("posts", "0005_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="tags.tag"),
        ),
    ]
