# Generated by Django 4.2.7 on 2023-12-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("posts", "0006_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="posts", to="tags.tag"),
        ),
    ]
